const ADDED = '+ ';
const REMOVED = '- ';
const UNCHANGED = '  ';

const INDENT_CHAR = ' ';
const SPACES_PER_INDENT = 4;
const SPACES_FOR_CHANGE_INFO = 2;

export { ADDED, REMOVED, UNCHANGED, INDENT_CHAR, SPACES_PER_INDENT, SPACES_FOR_CHANGE_INFO };
